version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask_app:
    build: .
    container_name: flask_container
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis        # Properly indented under depends_on
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: on-failure

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_container
    depends_on:
      - mongodb
      - redis
    environment:
      - PYTHONUNBUFFERED=1  
    command: celery -A app.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
      - ./logs:/app/logs 
    restart: always

volumes:
  mongo_data:
  